#!/bin/bash
CMD=$1
DIR=$PWD

if [ "$CMD" = "build" ]; then
	export NODE_ENV=production; cd node_modules/preact-boilerplate && rm -rf $DIR/build && node_modules/.bin/webpack --env.dir=$DIR ${@:2}
else
	cd node_modules/preact-boilerplate && node_modules/.bin/webpack-dev-server -d --progress --hot --inline --env.dir=$DIR ${@:2}
fi
