#!/bin/bash	
CMD=$1	
DIR=$PWD	

if [ "$CMD" = "build" ]; then
	cd node_modules/preact-boilerplate && rm -rf $DIR/build && NODE_ENV=production node --max-old-space-size=2048 node_modules/.bin/webpack --env dir=$DIR ${@:2} --progress
else	
	cd node_modules/preact-boilerplate && node --max-old-space-size=2048 node_modules/.bin/webpack serve --env dir=$DIR ${@:2} --progress --open 'Google Chrome'
fi